52 better foss
TalkAboutLocal/local-news-engine pull request #71
Opened 2016-11-21 10:34 UTC by robredpath

2017-01-05 18:20 UTC, Bjwebb requested changes
The commit history here is slightly confusing. I think maybe this could do with rebasing and maybe squashing.

2017-01-09 10:12 UTC, Bjwebb requested changes
Other than my two specific comments, this looks good, thanks.

2017-01-09 10:12 UTC, Bjwebb commented on README.md
> +  * **names.html** - A list of names which appear in two or more sources, and which may therefore be a lead to a story
Filenames here need updating to reflect https://github.com/TalkAboutLocal/local-news-engine/commit/1cf6a133ad32cc2250f728a64b0ba94c54bd3dc8

2017-01-13 17:13 UTC, robredpath commented
@Bjwebb Considered squashing. Looked at the commit history. Decided my sanity couldn't handle it.

2017-01-16 14:51 UTC, Bjwebb approved these changes

2017-01-16 14:51 UTC, merged